import { CustomerFeedbackCreateNestedManyWithoutRestaurantManagementsInput } from "./CustomerFeedbackCreateNestedManyWithoutRestaurantManagementsInput";
import { LoyaltyProgramCreateNestedManyWithoutRestaurantManagementsInput } from "./LoyaltyProgramCreateNestedManyWithoutRestaurantManagementsInput";

export type RestaurantManagementCreateInput = {
  customerFeedbacks?: CustomerFeedbackCreateNestedManyWithoutRestaurantManagementsInput;
  loyaltyPrograms?: LoyaltyProgramCreateNestedManyWithoutRestaurantManagementsInput;
};
