/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ReservationService } from "../reservation.service";
import { ReservationCreateInput } from "./ReservationCreateInput";
import { ReservationWhereInput } from "./ReservationWhereInput";
import { ReservationWhereUniqueInput } from "./ReservationWhereUniqueInput";
import { ReservationFindManyArgs } from "./ReservationFindManyArgs";
import { ReservationUpdateInput } from "./ReservationUpdateInput";
import { Reservation } from "./Reservation";
import { DeliveryIntegrationFindManyArgs } from "../../deliveryIntegration/base/DeliveryIntegrationFindManyArgs";
import { DeliveryIntegration } from "../../deliveryIntegration/base/DeliveryIntegration";
import { DeliveryIntegrationWhereUniqueInput } from "../../deliveryIntegration/base/DeliveryIntegrationWhereUniqueInput";

export class ReservationGrpcControllerBase {
  constructor(protected readonly service: ReservationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reservation })
  @GrpcMethod("ReservationService", "createReservation")
  async createReservation(
    @common.Body() data: ReservationCreateInput
  ): Promise<Reservation> {
    return await this.service.createReservation({
      data: {
        ...data,

        inventory: data.inventory
          ? {
              connect: data.inventory,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Reservation] })
  @ApiNestedQuery(ReservationFindManyArgs)
  @GrpcMethod("ReservationService", "reservations")
  async reservations(@common.Req() request: Request): Promise<Reservation[]> {
    const args = plainToClass(ReservationFindManyArgs, request.query);
    return this.service.reservations({
      ...args,
      select: {
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ReservationService", "reservation")
  async reservation(
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Reservation | null> {
    const result = await this.service.reservation({
      where: params,
      select: {
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ReservationService", "updateReservation")
  async updateReservation(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() data: ReservationUpdateInput
  ): Promise<Reservation | null> {
    try {
      return await this.service.updateReservation({
        where: params,
        data: {
          ...data,

          inventory: data.inventory
            ? {
                connect: data.inventory,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          inventory: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ReservationService", "deleteReservation")
  async deleteReservation(
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Reservation | null> {
    try {
      return await this.service.deleteReservation({
        where: params,
        select: {
          createdAt: true,
          id: true,

          inventory: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/deliveryIntegrations")
  @ApiNestedQuery(DeliveryIntegrationFindManyArgs)
  @GrpcMethod("ReservationService", "findManyDeliveryIntegrations")
  async findManyDeliveryIntegrations(
    @common.Req() request: Request,
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<DeliveryIntegration[]> {
    const query = plainToClass(DeliveryIntegrationFindManyArgs, request.query);
    const results = await this.service.findDeliveryIntegrations(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        reservation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deliveryIntegrations")
  @GrpcMethod("ReservationService", "connectDeliveryIntegrations")
  async connectDeliveryIntegrations(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() body: DeliveryIntegrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryIntegrations: {
        connect: body,
      },
    };
    await this.service.updateReservation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deliveryIntegrations")
  @GrpcMethod("ReservationService", "updateDeliveryIntegrations")
  async updateDeliveryIntegrations(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() body: DeliveryIntegrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryIntegrations: {
        set: body,
      },
    };
    await this.service.updateReservation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deliveryIntegrations")
  @GrpcMethod("ReservationService", "disconnectDeliveryIntegrations")
  async disconnectDeliveryIntegrations(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() body: DeliveryIntegrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryIntegrations: {
        disconnect: body,
      },
    };
    await this.service.updateReservation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
