/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { CustomerFeedbackService } from "../customerFeedback.service";
import { CustomerFeedbackCreateInput } from "./CustomerFeedbackCreateInput";
import { CustomerFeedbackWhereInput } from "./CustomerFeedbackWhereInput";
import { CustomerFeedbackWhereUniqueInput } from "./CustomerFeedbackWhereUniqueInput";
import { CustomerFeedbackFindManyArgs } from "./CustomerFeedbackFindManyArgs";
import { CustomerFeedbackUpdateInput } from "./CustomerFeedbackUpdateInput";
import { CustomerFeedback } from "./CustomerFeedback";
import { NotificationFindManyArgs } from "../../notification/base/NotificationFindManyArgs";
import { Notification } from "../../notification/base/Notification";
import { NotificationWhereUniqueInput } from "../../notification/base/NotificationWhereUniqueInput";

export class CustomerFeedbackGrpcControllerBase {
  constructor(protected readonly service: CustomerFeedbackService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerFeedback })
  @GrpcMethod("CustomerFeedbackService", "createCustomerFeedback")
  async createCustomerFeedback(
    @common.Body() data: CustomerFeedbackCreateInput
  ): Promise<CustomerFeedback> {
    return await this.service.createCustomerFeedback({
      data: {
        ...data,

        restaurantManagement: data.restaurantManagement
          ? {
              connect: data.restaurantManagement,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        restaurantManagement: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerFeedback] })
  @ApiNestedQuery(CustomerFeedbackFindManyArgs)
  @GrpcMethod("CustomerFeedbackService", "customerFeedbacks")
  async customerFeedbacks(
    @common.Req() request: Request
  ): Promise<CustomerFeedback[]> {
    const args = plainToClass(CustomerFeedbackFindManyArgs, request.query);
    return this.service.customerFeedbacks({
      ...args,
      select: {
        createdAt: true,
        id: true,

        restaurantManagement: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerFeedback })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CustomerFeedbackService", "customerFeedback")
  async customerFeedback(
    @common.Param() params: CustomerFeedbackWhereUniqueInput
  ): Promise<CustomerFeedback | null> {
    const result = await this.service.customerFeedback({
      where: params,
      select: {
        createdAt: true,
        id: true,

        restaurantManagement: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerFeedback })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CustomerFeedbackService", "updateCustomerFeedback")
  async updateCustomerFeedback(
    @common.Param() params: CustomerFeedbackWhereUniqueInput,
    @common.Body() data: CustomerFeedbackUpdateInput
  ): Promise<CustomerFeedback | null> {
    try {
      return await this.service.updateCustomerFeedback({
        where: params,
        data: {
          ...data,

          restaurantManagement: data.restaurantManagement
            ? {
                connect: data.restaurantManagement,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          restaurantManagement: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerFeedback })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("CustomerFeedbackService", "deleteCustomerFeedback")
  async deleteCustomerFeedback(
    @common.Param() params: CustomerFeedbackWhereUniqueInput
  ): Promise<CustomerFeedback | null> {
    try {
      return await this.service.deleteCustomerFeedback({
        where: params,
        select: {
          createdAt: true,
          id: true,

          restaurantManagement: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/notifications")
  @ApiNestedQuery(NotificationFindManyArgs)
  @GrpcMethod("CustomerFeedbackService", "findManyNotifications")
  async findManyNotifications(
    @common.Req() request: Request,
    @common.Param() params: CustomerFeedbackWhereUniqueInput
  ): Promise<Notification[]> {
    const query = plainToClass(NotificationFindManyArgs, request.query);
    const results = await this.service.findNotifications(params.id, {
      ...query,
      select: {
        createdAt: true,

        customerFeedback: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/notifications")
  @GrpcMethod("CustomerFeedbackService", "connectNotifications")
  async connectNotifications(
    @common.Param() params: CustomerFeedbackWhereUniqueInput,
    @common.Body() body: NotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notifications: {
        connect: body,
      },
    };
    await this.service.updateCustomerFeedback({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/notifications")
  @GrpcMethod("CustomerFeedbackService", "updateNotifications")
  async updateNotifications(
    @common.Param() params: CustomerFeedbackWhereUniqueInput,
    @common.Body() body: NotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notifications: {
        set: body,
      },
    };
    await this.service.updateCustomerFeedback({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/notifications")
  @GrpcMethod("CustomerFeedbackService", "disconnectNotifications")
  async disconnectNotifications(
    @common.Param() params: CustomerFeedbackWhereUniqueInput,
    @common.Body() body: NotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notifications: {
        disconnect: body,
      },
    };
    await this.service.updateCustomerFeedback({
      where: params,
      data,
      select: { id: true },
    });
  }
}
